name: React CI/CD

on:
  push:
    branches:
      - main  # main 브랜치로 푸시할 때 트리거
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server with password
        env:
          SERVER_IP: ${{ SERVER_PASSWORD.SERVER_IP }}
          SERVER_USER: ${{ SERVER_PASSWORD.SERVER_USER }}
          SERVER_PASSWORD: ${{ SERVER_PASSWORD.SERVER_PASSWORD }}
          DEPLOY_PATH: ${{ SERVER_PASSWORD.DEPLOY_PATH }}
        run: |
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "
            cd ${DEPLOY_PATH} &&
            git pull &&
            npm install &&
            pm2 restart all"
