name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy application
      env:
        SERVER_DDNS: ${{ secrets.SERVER_DDNS }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        # Build your project if necessary
        echo "Building project..."
        npm install
        npm run build

        # Upload build files to the server
        echo "Uploading files to server..."
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DDNS << EOF
          sudo mkdir -p /var/www/react-app
          sudo chown -R $SERVER_USER:$SERVER_USER /var/www/react-app
          sudo chmod -R 775 /var/www/react-app
        EOF
        sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no -r ./dist/* $SERVER_USER@$SERVER_DDNS:/var/www/react-app/

        # Restart server or application if needed
        echo "Restarting server..."
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DDNS << EOF
          sudo systemctl restart nginx
        EOF
